### PR TITLE
Adding Duo-Feeder

### PR DESCRIPTION
**Pull request by Cyrelion**

### CODE REVIEW

**Comment by Jezza34000** [comment]
Read this : https://github.com/RobertD502/petkitaio/pull/16
I also did this modification but you need a lot more to have a full support for this feeder

**Comment by Cyrelion** [comment]
Okay, I found a working library/fork from your lib, that was working, but after all the changes in your lib it's a little bit complex for me to reverse engineer the modifications :-(

I could share the client.py with you if you want to have a look?

**Comment by Jezza34000** [comment]
My repo had full support for D4sh (excluding image/video) before PetKit decided to deprecate certain version of the API (This f.. error 97).
I'm in the process of updating my repo at home, I'm testing all of that and if you're interested you can use my fork while waiting for the long-awaited official version from Robert :-)

**Comment by Cyrelion** [comment]
That would be great. Or you can open a pull request to merge your changes (after you've updated your branch with the latest release), so he just need to check your changes and we do not need to implement the wheel twice :-)

**Comment by Jezza34000** [comment]
No, I will not do a PR because in the various exchanges (Discord, Github) with @RobertD502  he does not want a PR or help on this subject. So I made my fork on my side while waiting for him to release his code :-)

**Comment by Cyrelion** [comment]
Okay @Jezza34000, didn't wanted to open old wounds again :-)

Thanks, I'll have a look at the fork too until the official release is done.

Btw. @RobertD502 or @Jezza34000 did someone start working on the new Ultra Pet Litter already? Do you need something to test with?

**Comment by Jezza34000** [comment]
@Cyrelion I push all my modification, working well for me :
 https://github.com/Jezza34000/home-assistant-petkit

**Comment by Cyrelion** [comment]
Can’t install your repository 😢

Tried to add this as a custom repository but download failed. Can I contact you somewhere else to not spam this pull request?

**Comment by Jezza34000** [comment]
Yes do you have Telegram or Discord ? i can help you

**Comment by Cyrelion** [comment]
https://t.me/Cyrelion

**Pull request closed without merging**
